name: Conditional Environment Variables

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Environment for Main Branch
        if: github.ref_name == 'main'
        run: echo "VAR1=Right Branch" >> $GITHUB_ENV

      - name: Set Environment for Other Branches
        if: github.ref_name != 'main'
        run: echo "VAR1=Wrong Branch" >> $GITHUB_ENV

      - name: Echo the Variable
        run: echo "VAR1 is $VAR1"
