name: Print Git Branch and Variables

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  print-branch-and-variables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine branch and set variables
        run: |
          echo "Current branch is ${{ github.ref_name }}"

          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "Using main environment variables"
            echo "ARTIFACT=${{ secrets.MAIN_ARTIFACT }}" >> $GITHUB_ENV
            echo "WORKSPACE=${{ secrets.MAIN_WORKSPACE }}" >> $GITHUB_ENV
            echo "CONNECTION_STRING=${{ secrets.MAIN_CONNECTION_STRING }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "acceptance" ]]; then
            echo "Using acceptance environment variables"
            echo "ARTIFACT=${{ vars.ACCEPTANCE_ARTIFACT }}" >> $GITHUB_ENV
            echo "WORKSPACE=${{ vars.ACCEPTANCE_WORKSPACE }}" >> $GITHUB_ENV
            echo "CONNECTION_STRING=${{ vars.ACCEPTANCE_CONNECTION_STRING }}" >> $GITHUB_ENV
          else
            echo "No specific environment variables for this branch."
          fi
        shell: bash

      - name: Set VAR1 Based on Branch
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "VAR1=Right Branch" >> $GITHUB_ENV
          else
            echo "VAR1=Wrong Branch" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Echo Environment Variables
        run: |
          echo "Artifact: $ARTIFACT"
          echo "Workspace: $WORKSPACE"
          echo "Connection String: $CONNECTION_STRING"
          echo "VAR1: $VAR1"
        shell: bash
        env:
          ARTIFACT: ${{ env.ARTIFACT }}
          WORKSPACE: ${{ env.WORKSPACE }}
          CONNECTION_STRING: ${{ env.CONNECTION_STRING }}
          VAR1: ${{ env.VAR1 }}
