name: Branch-Based Environment Setup

on:
  push:
    branches:
      - main
      - acceptance

jobs:
  setup-env:
    runs-on: ubuntu-latest
    # Specify the environment containing your secrets
    environment: 
      name: secrets  # Replace with actual environment name
      url: optional-deployment-url

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print current branch
        run: echo "Current branch is ${{ github.ref_name }}"

      - name: Set environment variables
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "ARTIFACT=${{ secrets.MAIN_ARTIFACT }}" >> $GITHUB_ENV
            echo "WORKSPACE=${{ secrets.MAIN_WORKSPACE }}" >> $GITHUB_ENV
            echo "CONNECTION_STRING=${{ secrets.MAIN_CONNECTION_STRING }}" >> $GITHUB_ENV
            echo "Using main environment variables"
          elif [[ "${{ github.ref_name }}" == "acceptance" ]]; then
            echo "ARTIFACT=${{ secrets.ACCEPTANCE_ARTIFACT }}" >> $GITHUB_ENV
            echo "WORKSPACE=${{ secrets.ACCEPTANCE_WORKSPACE }}" >> $GITHUB_ENV
            echo "CONNECTION_STRING=${{ secrets.ACCEPTANCE_CONNECTION_STRING }}" >> $GITHUB_ENV
            echo "Using acceptance environment variables"
          fi

      - name: Verify environment variables
        run: |
          echo "ARTIFACT: $ARTIFACT"
          echo "WORKSPACE: $WORKSPACE"
          echo "CONNECTION_STRING: $CONNECTION_STRING"
